Midi alt design
Jaxc/Magna pull request #1
Opened 2024-02-18 19:47 UTC by s-zaj

- use modern CMOS optocoupler that is faster, smaller, cheaper and does not need us to fiddle with a pull-up resistor
- add RX/TX activity monitor LEDs for easier debugging
- flip midi_in polarity labels

2024-02-19 12:27 UTC, Jaxc requested changes

2024-02-19 12:27 UTC, Jaxc commented on PCB/Magna/MCU.kicad_sch
Is there an actual change in this file? Otherwise lets remove it to keep the log a bit more clear :)

2024-02-19 12:27 UTC, Jaxc commented on PCB/Magna/MIDI.kicad_sch
Is there an actual change in this file? Otherwise lets remove it to keep the log a bit more clear :)

2024-02-19 12:27 UTC, Jaxc commented on PCB/Magna/Magna.kicad_pcb
Is there an actual change in this file? Otherwise lets remove it to keep the log a bit more clear :)

2024-02-19 12:27 UTC, Jaxc commented on PCB/Magna/Magna.kicad_sch
Is there an actual change in this file? Otherwise lets remove it to keep the log a bit more clear :)

2024-02-19 12:27 UTC, Jaxc commented on PCB/Magna/Power.kicad_sch
Is there an actual change in this file? Otherwise lets remove it to keep the log a bit more clear :)

2024-02-19 12:27 UTC, Jaxc commented on PCB/Magna/Usb.kicad_sch
Is there an actual change in this file? Otherwise lets remove it to keep the log a bit more clear :)

2024-02-19 12:27 UTC, Jaxc commented on PCB/Magna/human_interface.kicad_sch
Is there an actual change in this file? Otherwise lets remove it to keep the log a bit more clear :)

2024-02-19 12:27 UTC, Jaxc commented on PCB/Magna/power_led.kicad_sch
Is there an actual change in this file? Otherwise lets remove it to keep the log a bit more clear :)

2024-02-19 22:26 UTC, s-zaj commented
Wasn’t actually sure what to do about the autochanged files (thought maybe the kicad project would break if they were not committed together?) but let’s try

2024-02-20 08:26 UTC, Jaxc commented
It seems to be working fine with just the one file changed!

2024-02-20 13:59 UTC, merged